name: Deploy Website
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.johnb.io
        username: 73b3fc06@johnb.io
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/