name: Deploy Website
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.johnb.io
        username: 73b3fc06@johnb.io
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./                  # This points to where your files are locally
        server-dir: /public_html/      # This is where they should go on the server
        dangerous-clean-slate: true    # This will ensure clean deployment